# Generated by Django 3.0.2 on 2020-02-24 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admini',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('CNE', models.CharField(max_length=10)),
                ('CNI', models.IntegerField()),
                ('telephone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('demande', models.TextField()),
            ],
        ),
    ]
