# Generated by Django 3.0.2 on 2020-02-24 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_admini'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admini',
            new_name='Formule',
        ),
    ]
