# Generated by Django 3.0.2 on 2020-03-05 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200224_0935'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formule1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('chambre', models.IntegerField()),
                ('demande', models.TextField()),
                ('pavion', models.CharField(choices=[('1', 'pavion1'), ('2', 'pavion2'), ('3', 'pavion3')], max_length=7)),
            ],
        ),
    ]
