# Generated by Django 3.0.2 on 2020-03-08 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_formule1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formule2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='formule',
            name='telephone',
            field=models.IntegerField(max_length=10),
        ),
    ]
