# Generated by Django 3.0.2 on 2020-04-04 17:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200308_2002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formule',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='formule',
            old_name='demande',
            new_name='demand',
        ),
        migrations.RenameField(
            model_name='formule1',
            old_name='nom',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='formule1',
            old_name='chambre',
            new_name='bedroom',
        ),
        migrations.RenameField(
            model_name='formule1',
            old_name='demande',
            new_name='demand',
        ),
        migrations.RemoveField(
            model_name='formule',
            name='telephone',
        ),
        migrations.AddField(
            model_name='formule',
            name='phone',
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formule',
            name='CNI',
            field=models.CharField(max_length=10),
        ),
    ]
