# Generated by Django 3.0.2 on 2020-04-04 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200404_1959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formule1',
            old_name='Name',
            new_name='Nom',
        ),
    ]
