# Generated by Django 3.0.2 on 2020-04-04 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200404_2013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formule',
            old_name='Name',
            new_name='Full_name',
        ),
        migrations.RenameField(
            model_name='formule',
            old_name='phone',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='formule1',
            old_name='Nom',
            new_name='Full_name',
        ),
        migrations.RenameField(
            model_name='formule1',
            old_name='bedroom',
            new_name='bedroom_number',
        ),
    ]
