# Generated by Django 3.0.2 on 2020-04-04 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200404_2022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formule',
            old_name='nom',
            new_name='name',
        ),
    ]
