# Generated by Django 3.0.2 on 2020-04-04 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200404_2026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formule',
            old_name='name',
            new_name='Full_name',
        ),
        migrations.RenameField(
            model_name='formule',
            old_name='demande',
            new_name='demand',
        ),
        migrations.RenameField(
            model_name='formule',
            old_name='telephone',
            new_name='phone_number',
        ),
    ]
