# Generated by Django 3.0.2 on 2020-04-04 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20200404_2029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formule1',
            old_name='nom',
            new_name='Full_name',
        ),
        migrations.RenameField(
            model_name='formule1',
            old_name='chambre',
            new_name='bedroom_number',
        ),
        migrations.RenameField(
            model_name='formule1',
            old_name='demande',
            new_name='demand',
        ),
    ]
